language: java
jdk:
  - oraclejdk9
  - oraclejdk10

env:
  - GRADLE_VERSION=4.6
  - GRADLE_VERSION=4.7
  - GRADLE_VERSION=4.8.1
  - GRADLE_VERSION=4.9

matrix:
  exclude:
    - jdk: oraclejdk10
      env: GRADLE_VERSION=4.6

install: true
script: ./gradlew build -Ptest.skipAndroid=true -Ptest.gradle-version=$GRADLE_VERSION

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
